DELETE FROM student;
/*CREATE SEQUENCE IF NOT EXISTS SEQUENCE_GENERATOR START WITH 1;*/
CREATE TABLE IF NOT EXISTS student(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    age INT
);